import type { Metadata } from 'next'
import './globals.css'
import React from 'react';
import { Inder } from 'next/font/google'
import { Providers } from './components/providers';


const inder = Inder ({ 
  subsets: ['latin'],
  weight: ['400']
 })



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>    
        {children}
        </Providers>
        </body>
    </html>
  );
}

